blueprint:
  name: Styrbar Remote Control for AVATTO Dimmer
  description: >
    Provides integration and control for the IKEA E2001/E2002 Styrbar remote control.
    Allows for turning lights on/off, adjusting brightness.
    Designed for a Zigbee2MQTT Avatto Dimmers.
  domain: automation
  input:
    light_entity:
      name: Dimmer Light Entity
      description: Dimmer to control.
      selector:
        entity:
          domain: light
    dimmer_device:
      name: Dimmer Device
      description: Dimmer to control.
      selector:
        device: {}
    mqtt_device:
      name: Styrbar Remote Control
      description: The IKEA E2001/E2002 remote control.
      selector:
        device: {}
    delay_ms:
      name: Delay (ms) Between Steps
      description: "Delay in milliseconds between brightness adjustment steps."
      default: 300
      selector:
        number:
          min: 300
          max: 2000
          step: 100
          unit_of_measurement: "ms"

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_off
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_stop
    id: dim_stop

variables:
  light_entity: !input light_entity

action:
  - choose:
      - conditions:
          - condition: trigger
            id: light_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
      - conditions:
          - condition: trigger
            id: light_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
      - conditions:
          - condition: trigger
            id: dim_down
        sequence:
          - repeat:
              sequence:
                - device_id: !input dimmer_device
                  domain: light
                  entity_id: !input light_entity
                  type: brightness_decrease
                - delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: dim_stop
      - conditions:
          - condition: trigger
            id: dim_up
        sequence:
          - repeat:
              sequence:
                - device_id: !input dimmer_device
                  domain: light
                  entity_id: !input light_entity
                  type: brightness_increase
                - delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: dim_stop
mode: restart
